name = "SyntheticData"
uuid = "f46fe68f-9e63-4b46-8aa3-ae781f101a4f"
authors = ["Antonino DAnna <antonino.danna@estudiante.uam.es>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
